# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from pydantic import Field
from .aspect import Aspect
from .local_identifier import LocalIdentifier
from digital_twin_registry.dependencies import MyBaseModel


class DigitalTwin(MyBaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DigitalTwin - a model defined in OpenAPI

        id: The id of this DigitalTwin.
        description: The description of this DigitalTwin.
        manufacturer: The manufacturer of this DigitalTwin.
        local_identifiers: The local_identifiers of this DigitalTwin.
        aspects: The aspects of this DigitalTwin.
    """

    id: str
    description: str
    manufacturer: str
    local_identifiers: List[LocalIdentifier] = Field(None, alias='localIdentifiers')
    aspects: List[Aspect]

DigitalTwin.update_forward_refs()
