# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .http_method import HttpMethod
from digital_twin_registry.dependencies import MyBaseModel


class HttpEndpointCreate(MyBaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    HttpEndpointCreate - a model defined in OpenAPI

        url: The url of this HttpEndpointCreate.
        method: The method of this HttpEndpointCreate.
    """

    url: str
    method: HttpMethod

    @validator("url")
    def url_min_length(cls, value):
        assert len(value) >= 5
        return value

    @validator("url")
    def url_max_length(cls, value):
        assert len(value) <= 1000
        return value

HttpEndpointCreate.update_forward_refs()
