# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from .http_method import HttpMethod
from digital_twin_registry.dependencies import MyBaseModel


class HttpEndpoint(MyBaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    HttpEndpoint - a model defined in OpenAPI

        id: The id of this HttpEndpoint.
        url: The url of this HttpEndpoint.
        method: The method of this HttpEndpoint.
    """

    id: str
    url: str
    method: HttpMethod

HttpEndpoint.update_forward_refs()
