# coding: utf-8

from __future__ import annotations
from datetime import date, datetime
from enum import Enum  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class UrnBammComCatenaX010Context(str, Enum):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UrnBammComCatenaX010Context - a model defined in OpenAPI

    """
    as_designed = 'as-designed'
    as_planned = 'as-planned'
    as_built = 'as-built'
    as_maintained = 'as-maintained'
    as_recycled = 'as-recycled'


# UrnBammComCatenaX010Context.update_forward_refs()
