# coding: utf-8

from __future__ import annotations
from datetime import date, datetime
from enum import Enum  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class UrnBammComCatenaX010Type(str, Enum):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UrnBammComCatenaX010Type - a model defined in OpenAPI

    """
    assembly = 'Assembly'
    component = 'Component'
    software = 'Software'
    tool = 'Tool'
    raw_material = 'Raw Material'
    product = 'Product'
    piece_part = 'Piece Part'


# UrnBammComCatenaX010Type.update_forward_refs()
