# coding: utf-8

from __future__ import annotations
from ast import alias
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from pydantic import Field
from typetree.dependencies import SchemaConfig
from typetree.aspects.models.urn_bamm_com_catenax_traceability011_usage_characteristic import UrnBammComCatenaxTraceability011UsageCharacteristic


class UrnBammComCatenaxTraceability011SetofChildIdsCharacteristicChild(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UrnBammComCatenaxTraceability011SetofChildIdsCharacteristicChild - a model defined in OpenAPI

        created_on: The created_on of this UrnBammComCatenaxTraceability011SetofChildIdsCharacteristicChild.
        quantity: The quantity of this UrnBammComCatenaxTraceability011SetofChildIdsCharacteristicChild.
        modified_on: The modified_on of this UrnBammComCatenaxTraceability011SetofChildIdsCharacteristicChild [Optional].
        usage: The usage of this UrnBammComCatenaxTraceability011SetofChildIdsCharacteristicChild.
        child_catena_x_ids: The child_catena_x_ids of this UrnBammComCatenaxTraceability011SetofChildIdsCharacteristicChild.
    """

    created_on: Optional[datetime] = Field(None, alias='createdOn')
    quantity: Optional[float]
    modified_on: Optional[datetime] = Field(None, alias='modifiedOn')
    usage: Optional[UrnBammComCatenaxTraceability011UsageCharacteristic]
    child_catena_x_id: str = Field(None, alias='childCatenaXIds')

    class Config(SchemaConfig):
        ...

    """
    @validator("child_catena_x_id")
    def child_catena_x_id_pattern(cls, value):
        assert value is not None and re.match(r"^[0-9a-fA-F]{8}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{4}\\b-[0-9a-fA-F]{12}$", value)
        return value
    """

UrnBammComCatenaxTraceability011SetofChildIdsCharacteristicChild.update_forward_refs()
